version: "3"

services:
  app:
    container_name: train-ocr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - TESSTRAIN_FONT=AgencyFB Bold
      - TESSTRAIN_LANG=eng
      - TESSTRAIN_MAX_PAGES=10
      - TESSTRAIN_MAX_ITERATIONS=400
    command: sh start.sh